# Generated by Django 4.2.6 on 2023-11-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='link',
        ),
    ]
